import crafttweaker.item.IIngredient;

import mods.zenstages.ZenStager;

import scripts.crafttweaker.stages.stageArtificing;


static stagedItems as IIngredient[][string] = {
	stageArtificing.stage: [
		// EMBERS
		<embers:adhesive>,
		<embers:alchemic_waste>,
		<embers:alchemy_pedestal>,
		<embers:alchemy_tablet>,
		<embers:ancient_motive_core>,
		<embers:anti_tinker_lens>,
		<embers:archaic_brick>,
		<embers:archaic_circuit>,
		<embers:archaic_edge>,
		<embers:archaic_light>,
		<embers:ashen_amulet>,
		<embers:ashen_cloak_boots>,
		<embers:ashen_cloak_chest>,
		<embers:ashen_cloak_head>,
		<embers:ashen_cloak_legs>,
		<embers:ashen_cloth>,
		<embers:aspectus_copper>,
		<embers:aspectus_dawnstone>,
		<embers:aspectus_iron>,
		<embers:aspectus_lead>,
		<embers:aspectus_silver>,
		<embers:auto_hammer>,
		<embers:axe_clockwork>,
		<embers:axe_dawnstone>,
		<embers:beam_cannon>,
		<embers:beam_splitter>,
		<embers:bin>,
		<embers:blasting_core>,
		<embers:blend_caminite>,
		<embers:block_caminite_brick>,
		<embers:block_caminite_brick_slab>,
		<embers:block_caminite_brick_slab_double>,
		<embers:block_dawnstone>,
		<embers:block_furnace>,
		<embers:block_lantern>,
		<embers:block_tank>,
		<embers:boiler>,
		<embers:breaker>,
		<embers:brick_caminite>,
		<embers:caminite_lever>,
		<embers:caster_orb>,
		<embers:catalytic_plug>,
		<embers:catalyzer>,
		<embers:charger>,
		<embers:cinder_plinth>,
		<embers:clockwork_attenuator>,
		<embers:codex>,
		<embers:combustor>,
		<embers:copper_cell>.withTag({emberCapacity: 24000.0, ember: 0.0}),
		<embers:copper_cell>.withTag({emberCapacity: 24000.0, ember: 24000.0}),
		<embers:creative_ember_source>,
		<embers:creative_heat>,
		<embers:crystal_cell>,
		<embers:crystal_ember>,
		<embers:dawnstone_anvil>,
		<embers:dawnstone_mail>,
		<embers:diffraction_barrel>,
		<embers:dust_ash>,
		<embers:dust_ember>,
		<embers:dust_metallurgic>,
		<embers:eldritch_insignia>,
		<embers:ember_activator>,
		<embers:ember_amulet>,
		<embers:ember_belt>,
		<embers:ember_bore>,
		<embers:ember_bulb>.withTag({emberCapacity: 1000.0, ember: 0.0}),
		<embers:ember_bulb>.withTag({emberCapacity: 1000.0, ember: 1000.0}),
		<embers:ember_cartridge>.withTag({emberCapacity: 6000.0, ember: 0.0}),
		<embers:ember_cartridge>.withTag({emberCapacity: 6000.0, ember: 6000.0}),
		<embers:ember_cluster>,
		<embers:ember_detector>,
		<embers:ember_emitter>,
		<embers:ember_funnel>,
		<embers:ember_gauge>,
		<embers:ember_injector>,
		<embers:ember_jar>.withTag({emberCapacity: 2000.0, ember: 0.0}),
		<embers:ember_jar>.withTag({emberCapacity: 2000.0, ember: 2000.0}),
		<embers:ember_pipe>,
		<embers:ember_pulser>,
		<embers:ember_receiver>,
		<embers:ember_relay>,
		<embers:ember_ring>,
		<embers:ember_siphon>,
		<embers:explosion_charm>,
		<embers:explosion_pedestal>,
		<embers:field_chart>,
		<embers:flame_barrier>,
		<embers:fluid_dropper>,
		<embers:fluid_gauge>,
		<embers:fluid_transfer>,
		<embers:focal_lens>,
		<embers:gear_dawnstone>,
		<embers:geo_separator>,
		<embers:glimmer_lamp>,
		<embers:glimmer_shard>,
		<embers:golems_eye>,
		<embers:grandhammer>,
		<embers:heat_coil>,
		<embers:hoe_dawnstone>,
		<embers:ignition_cannon>,
		<embers:inferno_forge>,
		<embers:inflictor_gem>,
		<embers:ingot_dawnstone>,
		<embers:intelligent_apparatus>,
		<embers:isolated_materia>,
		<embers:item_dropper>,
		<embers:item_pipe>,
		<embers:item_pump>,
		<embers:item_request>,
		<embers:item_transfer>,
		<embers:jet_augment>,
		<embers:large_tank>,
		<embers:mech_accessor>,
		<embers:mech_actuator>,
		<embers:mech_actuator_single>,
		<embers:mech_core>,
		<embers:mechanical_pump>,
		<embers:mini_boiler>,
		<embers:mixer>,
		<embers:nonbeliever_amulet>,
		<embers:nugget_dawnstone>,
		<embers:pickaxe_clockwork>,
		<embers:pickaxe_dawnstone>,
		<embers:pipe>,
		<embers:plate_caminite>,
		<embers:plate_caminite_raw>,
		<embers:plate_dawnstone>,
		<embers:pump>,
		<embers:reaction_chamber>,
		<embers:reactor>,
		<embers:resonating_bell>,
		<embers:seed>,
		<embers:seed_aluminum>,
		<embers:seed_copper>,
		<embers:seed_dawnstone>,
		<embers:seed_gold>,
		<embers:seed_iron>,
		<embers:seed_lead>,
		<embers:seed_nickel>,
		<embers:seed_silver>,
		<embers:seed_tin>,
		<embers:shard_ember>,
		<embers:shifting_scales>,
		<embers:shovel_dawnstone>,
		<embers:spark_plug>,
		<embers:staff_ember>,
		<embers:stairs_caminite_brick>,
		<embers:stamp_bar>,
		<embers:stamp_bar_raw>,
		<embers:stamp_flat>,
		<embers:stamp_flat_raw>,
		<embers:stamp_gear>,
		<embers:stamp_gear_raw>,
		<embers:stamp_plate>,
		<embers:stamp_plate_raw>,
		<embers:stamper>,
		<embers:stamper_base>,
		<embers:steam_engine>,
		<embers:stirling>,
		<embers:stone_edge>,
		<embers:stone_valve>,
		<embers:superheater>,
		<embers:sword_dawnstone>,
		<embers:tinker_hammer>,
		<embers:tinker_lens>,
		<embers:turret>,
		<embers:tyrfing>,
		<embers:vacuum>,
		<embers:wall_caminite_brick>,
		<embers:wildfire_core>,
		<embers:winding_gears>,

		//SOOT
		<soot:alchemy_gauge>,
		<soot:alchemy_globe>,
		<soot:caminite_clay>,
		<soot:caminite_large_tile>,
		<soot:caminite_large_tile_slab>,
		<soot:caminite_large_tile_stairs>,
		<soot:caminite_tiles>,
		<soot:caminite_tiles_slab>,
		<soot:caminite_tiles_stairs>,
		<soot:decanter>,
		<soot:distillation_pipe>,
		<soot:eitr>,
		<soot:ember_burst>,
		<soot:essence>.withTag({type: "chaos"}),
		<soot:essence>.withTag({type: "cloud"}),
		<soot:essence>.withTag({type: "death"}),
		<soot:essence>.withTag({type: "experience"}),
		<soot:essence>.withTag({type: "extract"}),
		<soot:essence>.withTag({type: "fire"}),
		<soot:essence>.withTag({type: "glass"}),
		<soot:essence>.withTag({type: "haste"}),
		<soot:essence>.withTag({type: "ice"}),
		<soot:essence>.withTag({type: "inversion"}),
		<soot:essence>.withTag({type: "lifedrinker"}),
		<soot:essence>.withTag({type: "null"}),
		<soot:essence>.withTag({type: "poison"}),
		<soot:essence>.withTag({type: "projectile"}),
		<soot:essence>.withTag({type: "regeneration"}),
		<soot:essence>.withTag({type: "slowness"}),
		<soot:essence>.withTag({type: "sour"}),
		<soot:essence>.withTag({type: "speed"}),
		<soot:essence>.withTag({type: "sweet"}),
		<soot:essence>.withTag({type: "toxin"}),
		<soot:essence>.withTag({type: "vile"}),
		<soot:essence>.withTag({type: "wither"}),
		<soot:ingot_antimony>,
		<soot:insulation>,
		<soot:mug>,
		<soot:mug>.withTag({Fluid: {FluidName: "boiling_wort", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "boiling_potato_juice", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "boiling_wormwood", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "boiling_beetroot_soup", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "dwarven_ale", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "vodka", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "inner_fire", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "umber_ale", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "absinthe", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "methanol", Amount: 250}}),
		<soot:mug>.withTag({Fluid: {FluidName: "snowpoff", Amount: 250}}),
		<soot:mundane_stone>,
		<soot:redstone_bin>,
		<soot:scale>,
		<soot:signet_antimony>,
		<soot:stamp_nugget>,
		<soot:stamp_nugget_raw>,
		<soot:stamp_text>,
		<soot:stamp_text_raw>,
		<soot:still>,
		<soot:sulfur>,
		<soot:sulfur_clump>,
		<soot:sulfur_ore>,
		<soot:witch_fire>,
		<soot:wrought_platform>,
		<soot:wrought_platform_slab>,
		<soot:wrought_tile>,
	]
};

static stagedRecipes as string[][string] = {
	stageArtificing.stage: [
		// EMBERS
		"embers:ashen_brick"
	]
};


function init() {
	for stageName, items in stagedItems {
		ZenStager.getStage(stageName).addIngredients(items);
	}
	for stageName, recipe_list in stagedRecipes {
		for recipe in recipe_list {
			ZenStager.getStage(stageName).addRecipeName(recipe);
		}
	}
}
